# Generated by Django 5.1.2 on 2024-10-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='food_id',
            new_name='food_info',
        ),
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='order_id',
            new_name='order_info',
        ),
    ]
