# Generated by Django 5.1.2 on 2024-10-31 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_food_id_orderitemmodel_food_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
