# Generated by Django 5.1.2 on 2024-10-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_orderitemmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
