# Generated by Django 5.1.2 on 2024-11-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_orderitemmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
