# Generated by Django 5.1.2 on 2024-11-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
